version: "2"
services:
  web-client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"

  web-server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    links:
      - mongo

  mongo:
    image: mongo
    # ports:
    #   - "27017:27017"
    logging:
      driver: none
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017 
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: fairlyTail
    logging:
      driver: none

volumes:
  mongo_db: